### ISSUE TITLE
how to export workflow in comfyUI

### ISSUE THREAD

**Issue by neophack** [Visionatrix/Visionatrix#145]
I modify workflow in comfyUI, but I save workflow.json can't work. how to export workflow in comfyUI?
![image](https://github.com/user-attachments/assets/2a5f4457-6310-47e8-83f8-009f7d21f486)
![image](https://github.com/user-attachments/assets/95a0331f-112c-4d80-9665-0d7546b99460)

**Comment by bigcat88** [comment]
Visionatrix accepts workflows in the "ComfyUI API" format.
Just resave you workflow in API format.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/f4dc1e62-ff9d-4a3e-b4a1-471688a2af3d">

There is request in ComfyUI for functionality to do automatic conversion, to help "API services" can support usual workflow format: https://github.com/comfyanonymous/ComfyUI/issues/1112

**Comment by neophack** [comment]
good
